/**
 *  APEG Tool Parser
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class Annotation extends StateFullBaseParser{

      public Annotation(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult a(Object[] v){
         startRule("a");
         Object[] copy;
         Object[] list_param;
         mkBacktracPoint();
         v_restore = v.copy();
         b(list_param); 
         if(isOk()){
             match("1"); 
         } 
         if(isOk()){ return success();}
         restore();
         mkBacktracPoint();
         v_restore = v.copy();
         b(list_param); 
         if(isOk()){
             match("2"); 
         } 
         if(isOk()){ return success();}
         if(isOk()){return success();} else{return fail();}
      }

      public PegResult b(Object[] v){
         startRule("b");
         Object[] copy;
         Object[] list_param;
         match("b");
         if(isOk()){return success();} else{return fail();}
      }
}