/**
 *  APEG Tool Parser 
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class Choiceback extends StateFullBaseParser{

      public Choiceback(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult a(){
         startRule("a");
         b();
         if(isOk()){return success();} else{return fail();}      
      }

      public PegResult b(){
         startRule("b");
         mkBacktracPoint();
         match("0");
         if(isOk()){
             match("0");
             if(isOk()){
                 b(); 
             } 
         } 
         if(isOk()){ return success();}
         restore();    
         mkBacktracPoint();
         mkBacktracPoint();
         match("1");
         if(isOk()){
             match("1");
             if(isOk()){
                 match("0");
                 if(isOk()){
                     match("0");
                     if(isOk()){
                         b(); 
                     } 
                 }  
             } 
         } 
         if(isOk()){ return success();}
         restore();    
         mkBacktracPoint();
         match("2");
         if(isOk()){
             match("2");
             if(isOk()){
                 match("1");
                 if(isOk()){
                     match("1");
                     if(isOk()){
                         match("0");
                         if(isOk()){
                             match("0");
                             if(isOk()){
                                 b(); 
                             } 
                         }  
                     } 
                 }  
             } 
         } 
         if(isOk()){ return success();}
         if(isOk()){ return success();}
         if(isOk()){return success();} else{return fail();}      
      } 
}