/**
 *  APEG Tool Parser 
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class Expression extends StateFullBaseParser{

      public Expression(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult s(){
         startRule("s");
         if(isOk()){return success();} else{return fail();}      
      } 
}