/**
 *  APEG Tool Parser
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class LitExpr extends StateFullBaseParser{

      public LitExpr(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult s(){
         startRule("s");
         mkBacktracPoint();
         match("0");
         if(isOk()){
              (int) v[0]  - (int) v[0]  
         } 
         if(isOk()){ return success();}
         restore();
         mkBacktracPoint();
         match("1");
         if(isOk()){
             1 
         } 
         if(isOk()){ return success();}
         if(isOk()){return success();} else{return fail();}
      }
}