package apeg.rts;

/**
 *  APEG Tool Parser
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class Annotation extends StateFullBaseParser{

      public Annotation(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult a(){
         startRule("a");
         mkBacktracPoint();
         b();
         if(isOk()){
             match("1"); 
         } 
         if(isOk()){ return success();}
         restore();
         mkBacktracPoint();
         b();
         if(isOk()){
             match("2"); 
         } 
         if(isOk()){ return success();}
         if(isOk()){return success();} else{return fail();}
      }

      public PegResult b(){
         startRule("b");
         match("b");
         if(isOk()){return success();} else{return fail();}
      }
}
