package apeg.rts;
/**
 *  APEG Tool Parser 
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class Peg extends StateFullBaseParser{

      public Peg(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult s(){
         startRule("s");
         match("foo");
         if(isOk()){
             mkBacktracPoint();
             s();
             if(isOk()){ dismissBacktracPoint();}
             else{ restore(); done(); } 
             if(isOk()){
                 match("bar"); 
             } 
         } 
         if(isOk()){return success();} else{return fail();}      
      } 
}