package apeg.rts;

/**
 *  APEG Tool Parser 
 *  This code was automatically generated by APEG Parser Generator.
 *  Last modification 27/04/2018
 */
public class SimpleTest extends StateFullBaseParser{

      public SimpleTest(String fname) {
          super(fname);
          startRule("root");
      }

      public PegResult s(){
         startRule("s");
         match("abc");
         if(isOk()){
             a(); 
         } 
         if(isOk()){ return success();}else{return fail();}
      }

      public PegResult a(){
         startRule("a");
         mkBacktracPoint();
         match("010");
         if(isOk()){
            match("10"); 
         }
         while(isOk()){
            dismissBacktracPoint();
            mkBacktracPoint();
            match("010");
            if(isOk()){
               match("10"); 
            }
         }
         restore();
         done();
         if(isOk()){
             match("01001"); 
         } 
         if(isOk()){ return success();}else{return fail();}
      } 
}
